/*
s->cAd
A->ab/a */
#include<stdio.h>
#include<string.h>
int A();
void parse();
char str[15];
int isave,curr_ptr=0;
int c=1;
int main(void)
{
    printf("1.S->cAd\n2.A->ab/a\n");
    //printf("this is parser for the above grammar:\n");
    printf("Enter any string:");
    scanf("%s",str);
    while(curr_ptr<strlen(str))
    {
        //S has only one immediate derivation which is cAd
        //match with c
        if (str[curr_ptr]=='c')
        {
            curr_ptr++;
            //call function to match A
            if (A()) //checking the productions of A->ab/a
            {
                curr_ptr++;
                //match d
                if (str[curr_ptr]=='d' && str[curr_ptr+1]=='\0')
                {
                    //success
                    printf("String is accepted by the grammar\n");
                    parse();
                    return 1;
                }
                else break;
            }
            else break;
        }
        else break;
    }
    //incase any of them fail to match return negatively.
    printf("String is not accepted by the grammar");
    return 0;
}

int A()
//sub function A()
{
    //this function matches all terminal strings generated by the variable
   
    isave=curr_ptr;
    //match with a and advance and match with b. If successful return
   
    if (str[curr_ptr]=='a')
    {
        curr_ptr++;
        if(str[curr_ptr]=='b')
        {
            c=1;
            return 1;
        }
           
    }
    curr_ptr=isave; //return to start
    //check if a is matched and return accordingly.
    if(str[curr_ptr]=='a')
    {
        c=2;
        return 1;
    }
    else
        return 0;
}

void parse()
{
    printf("The productions used are \n");
    printf("S -> cAd\n");
    if(c==1)
        printf("A -> ab\n");
    else
        printf("A -> a\n");

}
